#!/usr/bin/env python3
  
import os
import subprocess
from colorama import Fore
LOG_PATH="/RACKLOG/quanta/"

def do_grep(files,key):
    for serialNum,list in files.items():
        print(Fore.GREEN + f"-------------RESULT:{serialNum}-------------------" + Fore.WHITE)
        for i in list:
            cmd=f"grep -w -B 10 -A 10 '{key}' {i}"
            print(Fore.BLUE + f"*{i}*" + Fore.WHITE)
            os.system(cmd)
def search_logs_location(logs_sn):
    logs_loc={}
    for each in logs_sn:
        pattern =f"*{each[-12:]}*"
        result=subprocess.Popen(['find',LOG_PATH,'-type','f','-iname',pattern],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        output=result.communicate()
        string = output[0].decode('utf-8')
        list_str=string.split('\n')
        if len(list_str) > 1:
            list_str.pop(-1)
            logs_loc[each]=list_str
        else:
            print("-------------------Warning------------------------------")
            print(f"No Logs Found For '{each}'")
            print("--------------------------------------------------------")
            continue
    return logs_loc

if __name__ == '__main__':

        inputs = []
        sn = input("Please enter sn that you want to use grep:\n").strip().lower()

        while len(sn) != 0:
            inputs.append(sn)
            sn=input().strip().lower()
#        result_files=search_logs_location(inputs)
#        if not bool(result_files):
#            exit(1)
        keyword=input("What is the key word or phase:\n")
        while len(keyword) == 0:
            keyword=input("Please re-enter the key word:\n")
        result_files=search_logs_location(inputs)
        if not bool(result_files):
            exit(1)
        do_grep(result_files,keyword)
