#!/bin/bash
Red='\033[0;31m'
NC='\033[0m'
Green='\033[0;32m'
Orange='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
LGray='\033[0;37m'
DGray='\033[1;30m'
LRed='\033[1;31m'
LGreen='\033[1;32m'
Yellow='\033[1;33m'
LBlue='\033[1;34m'
LPurple='\033[1;35m'
LCyan='\033[1;36m'
White='\033[1;37m'
if [ "$1" == "" ];then
  echo -e "${LCyan}i4${NC} is a tool used to logging into systems with just a serversn."
  exit 1
fi

if [ "$1" == "-d" ] || [ "$1" == "-s" ]; then
	if [ -z "$2" ];then
		echo -e "${Red}Missing SN. Please enter one.${NC}"
		exit
	else		
       	 	path=$(find /WIN/ -name $2.txt|grep -i response/config)
	fi
elif [ "$1" == "-l10" ]; then
	if [ -z "$2" ];then
                echo -e "${Red}Missing MAC Address. Please enter one.${NC}"
                exit
        else
		path="L10 mode activated!"
	fi
else
	path=$(find /WIN/ -name $1.txt|grep -i response/config)
fi
#echo $path

if (($(grep -c . <<<"$path") > 1 )); then
	echo -e "${Yellow}MULTIPLE Config files found!"
	echo -e "===============================${NC}"
	#IFS=" " read -ra file_array <<< "$path"
	file_array=($(echo $path | tr "\n" "\n"))
	#echo ${file_array[@]}
	declare -i counter="0"
	echo "Please choose the correct project or configuration file: "
	for file in "${file_array[@]}"
	do
		echo -e "${Green}$counter${NC}: $file"
		counter+=1
	done
	echo -e "${Orange}Select the number associated with the file:${NC}"
	read selection
	#echo -e "${LGreen}$selection ${NC} was selected!"
	path=${file_array[$selection]}
elif (($(grep -c . <<<"$path") == 1 )); then
	echo "SINGLE CONFIG FILE FOUND"
	echo "================================"
else
	echo -e "${LRed}NO CONFIG FILE FOUND!${NC}"
	echo "================================"
	echo "You might be in the wrong pxe or you're using the wrong SN!"
	exit 1

fi

echo -e "Config file used: ${LCyan}$path${NC}"
if [ "$1" == "-d" ]; then
	BMCMAC=$(cat $path|grep ETH0)
	MAC=${BMCMAC:5:2}:${BMCMAC:7:2}:${BMCMAC:9:2}:${BMCMAC:11:2}:${BMCMAC:13:2}:${BMCMAC:15:2}
elif [ "$1" == "-s" ]; then
	BMCMAC=$(cat $path|grep SWITCHMAC)
	if [ -z "$BMCMAC" ];then
		echo -e "${LRed}Wasn't able to find a a switch MAC within the config file.${NC}"
		exit 1
	fi
	#echo $BMCMAC
	MAC=${BMCMAC:10:2}:${BMCMAC:12:2}:${BMCMAC:14:2}:${BMCMAC:16:2}:${BMCMAC:18:2}:${BMCMAC:20:2}
elif [ "$1" == "-l10" ]; then
	MAC=$2
	echo $MAC
else
	BMCMAC=$(cat $path|grep ETH0)
	MAC=${BMCMAC:5:2}:${BMCMAC:7:2}:${BMCMAC:9:2}:${BMCMAC:11:2}:${BMCMAC:13:2}:${BMCMAC:15:2}
fi
echo -e "MAC Address found: ${LCyan}$MAC${NC}"
ip=$(ip neigh|grep -v fe|grep -i $MAC| cut -d " " -f1)
#readarray -t ip <<<"$raw_ip"
#echo "IP found: $ip"
ip=($(echo $ip | tr "\n" "\n"))


if [ -z "$ip" ];then 
	echo -e "${Yellow}Could not find anything in IP neighbor. Trying dhcpd leases...${NC}"
	line_number=$(grep $MAC -i -n /var/lib/dhcpd/dhcpd.leases)
	IFS=":" read -ra split<<< "$line_number"
	line_number=$((${split[0]}-6))
	line=$(cat -n /var/lib/dhcpd/dhcpd.leases|grep $line_number)
	IFS=" " read -ra split<<< "$line"
	ip=${split[1]}

elif [ ! -z "${ip[1]}" ];then
	echo -e "${Yellow}Multiple Addresses were found:${NC}"
  	declare -i counter="0"
	#echo ${ip[2]}
	for thing in "${ip[@]}"
	do 
		echo -e "${Green}$counter${NC}: $thing"
		counter+=1
	done
	#echo "x: None of these"
	echo -e "${Yellow}Please select the correct one: ${NC}"
	read selection
	#re='^[0-9]+$'
	#if [ $selection == "x"]; then
	#        echo "Checking DHCPD Leases!"
	#        line_number=$(grep $MAC -i -n /var/lib/dhcpd/dhcpd.leases)
	#        IFS=":" read -ra split<<< "$line_number"
	#    	line_number=$((${split[0]}-6))
	#        line=$(cat -n /var/lib/dhcpd/dhcpd.leases|grep $line_number)
       # 	IFS=" " read -ra split<<< "$line"
#	        ip=${split[1]}
	ip=${ip[$selection]}
	
	echo -e "${LGreen}$ip${NC} was selected!"
fi	 
echo -e "IP Being used is: ${LGreen}$ip${NC}"
#sshpass -p 'root' ssh-copy-id -o 'StrictHostKeyChecking no' $ip
if [ "$1" == "-d" ];then
	sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
elif [ "$1" == "-l10" ];then
	BMCIP=$(sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip ". getMBinfo"|grep "BMCIP")
	ip=${BMCIP:6:40}
	echo -e "IP Being used is: ${LGreen}$ip${NC}"
	sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
else
	sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
fi

