#!/bin/bash

if [ ! $1 ]; then
        echo -e "
                USAGE:

                  jumpin MAC <aabbccdd> or IP <aa.bb.cc.dd> or rm 

                  For C2798:

                  jumpin BMC_MAC cp #Jump Into CP card

                  jumpin <Location of RM> rm #Jump Into RM

                DESCRIPTION:

                  This scipt will help you to jump in server in L10 by
                  either Eth port or BMC port. The MAC address could
                  be queried by UUT SN at \033[1;32mQUERY->serverinfo->MSF_LinkComp.\033[0m
		 "
   exit 1
fi

declare -A mac_mapping 

source rm_mac.txt

input=$(echo "$1" | tr '[:lower:]' '[:upper:]')
Mac_addr="${input:0:2}:${input:2:2}:${input:4:2}:${input:6:2}:${input:8:2}:${input:10:2}"
two_digit="${input:0:2}"

find_mac_info(){
  dir_dhcplease="/var/lib/dhcp/dhcpd.leases"
  formatted_input=$(echo $Mac_addr |tr [:upper:] [:lower:])
    if [ ! -f "$dir_dhcplease" ]; then
       echo "No dhcplease found in pxe"
    else
         information=$(grep -A2 -B8 $formatted_input $dir_dhcplease)
         if [ ! "$information" ]; then
            echo "No MAC address found"
            exit 1
         fi
    fi
}
isbmcip(){
  echo -e "\033[1;95mCHECKING IP("$ip")........\033[0m"
  echo -e "\033[1;95mPLEASE WAIT........\033[0m"
  checking=$(timeout 4s ipmitool -H $ip -U admin -P admin mc info | grep Device)
  ping_ip=$(timeout 2s ping $ip )
  if [ ! "$ping_ip" ];then
     echo -e "\033[0;31mIP is not pingable.\033[0m"
     exit 1
  else
     if [ "$checking" ]; then
        true
     else
        false
     fi
  fi
}
if [ ! $2 ] || [ $2 == cp ];then
   if [ $two_digit = 10 ]; then
      echo -e "\033[1;32m*****************************\033[0m"
      echo -e "\033[1;32m*START ACCESSING BY ETH PORT*\033[0m"
      echo -e "\033[1;32m*****************************\033[0m"
      sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$1
   else
      find_mac_info
      info=$information
      ip=$(echo "$info" | grep -B6 "binding state active" | grep lease | tail -n 1 | awk 'NR==1{print $2}')
      if isbmcip; then
         if [ -n "$2" ] && [ "$2" == "cp" ];then
            echo -e "\033[1;33m*****************************\033[0m"
            echo -e "\033[1;33m*  ACCESSING INTO CP CARD   *\033[0m"
            echo -e "\033[1;33m*****************************\033[0m"
            sshpass -p 'admin' ssh -p 8295 -o 'StrictHostKeyChecking no' admin@$ip
         else
            echo -e "\033[1;33m*****************************\033[0m"
            echo -e "\033[1;33m*START ACCESSING BY BMC PORT*\033[0m"
            echo -e "\033[1;33m*****************************\033[0m"
            ipmitool -H $ip -U admin -P admin -I lanplus sol activate
         fi
      else
         echo -e "\033[1;34m*****************************\033[0m"
         echo -e "\033[1;34m*START ACCESSING BY ETH PORT*\033[0m"
         echo -e "\033[1;34m*****************************\033[0m"
         sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
      fi
   fi

elif [ "$input" == RM   ]; then
   echo -e "\033[1;36m*****************************\033[0m"
   echo -e "\033[1;36m*     START LOGIN TO RM     *\033[0m"
   echo -e "\033[1;36m*****************************\033[0m"
   rm_mac=$2
   Mac_addr="${rm_mac:0:2}:${rm_mac:2:2}:${rm_mac:4:2}:${rm_mac:6:2}:${rm_mac:8:2}:${rm_mac:10:2}"
   find_mac_info
   info=$information
   ip=$(echo "$info" | grep -B6 "binding state active" | grep lease | tail -n 1 | awk '{print $2}')
   sshpass -p '$pl3nd1D' ssh -o 'StrictHostKeyChecking no' root@$ip

elif [ $2 == rm ] && [[ "${mac_mapping["$input"]+exists}" ]];then
   input=${mac_mapping[$input]}
   Mac_addr="${input:0:2}:${input:2:2}:${input:4:2}:${input:6:2}:${input:8:2}:${input:10:2}"
   find_mac_info
   info=$information
   ip=$(echo "$info" | grep -B6 "binding state active" | grep lease | tail -n 1 | awk '{print $2}')

   echo -e "\033[1;33m*****************************\033[0m"
   echo -e "\033[1;33m*  ACCESSING INTO RM        *\033[0m"
   echo -e "\033[1;33m*****************************\033[0m"
   sshpass -p '$pl3nd1D' ssh -o 'StrictHostKeyChecking no' root@$ip
else
   echo "You are might not on right PXE"

fi
