#!/bin/bash
Red='\033[0;31m'
NC='\033[0m'
Green='\033[0;32m'
Orange='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
LGray='\033[0;37m'
DGray='\033[1;30m'
LRed='\033[1;31m'
LGreen='\033[1;32m'
Yellow='\033[1;33m'
LBlue='\033[1;34m'
LPurple='\033[1;35m'
LCyan='\033[1;36m'
White='\033[1;37m'

if [ "$1" == "" ]; then
	echo -e "${LCyan}rr${NC} is a tool used to logging into rm with just a serversn."
	exit 1
fi

if [ "$1" == "-d" ] || [ "$1" == "-s" ]; then
	if [ -z "$2" ]; then
		echo -e "${Red}Missing SN. Please enter one.${NC}"
		exit
	else
		path=$(find /WIN/ -name $2.txt | grep -i response/config)
	fi
elif [ "$1" == "-l10" ]; then
	if [ -z "$2" ]; then
		echo -e "${Red}Missing MAC Address. Please enter one.${NC}"
		exit
	else
		path="L10 mode activated!"
	fi
else
	path=$(find /WIN/ -name $1.txt | grep -i response/config)
fi

if (($(grep -c . <<<"$path") > 1)); then
	echo -e "${Yellow}MULTIPLE Config files found!"
	echo -e "===============================${NC}"
	file_array=($(echo $path | tr "\n" "\n"))
	declare -i counter="0"
	echo "Please choose the correct project or configuration file: "
	for file in "${file_array[@]}"; do
		echo -e "${Green}$counter${NC}: $file"
		counter+=1
	done
	echo -e "${Orange}Select the number associated with the file:${NC}"
	read selection
	path=${file_array[$selection]}
elif (($(grep -c . <<<"$path") == 1)); then
	echo "SINGLE CONFIG FILE FOUND"
	echo "================================"
else
	echo -e "${LRed}NO CONFIG FILE FOUND!${NC}"
	echo "================================"
	echo "You might be in the wrong pxe or you're using the wrong SN!"
	exit 1

fi

model=$(grep PARTN "$path" | awk -F'=' '{print $2}' | tr -d '\r')
location=$(grep LOCATION "$path" | sed 's/[^0-9]//g' | tr -d '\r')
echo -e "Config file used: ${LCyan}$path${NC}"

# Takes the BMCMAC string, extracts the mac and formats it
#
# Argument 1: Config line containing key and BMC MAC value
#
# Outputs: Formatted MAC string
parse_bmc_mac() {
	BMCMAC=$(echo $1 | rev | cut -d "=" -f 1 | rev)
	echo ${BMCMAC:0:2}:${BMCMAC:2:2}:${BMCMAC:4:2}:${BMCMAC:6:2}:${BMCMAC:8:2}:${BMCMAC:10:2}
}

# Used for racks with two rack managers.
# Finds the MAC address for the server based on its location. The split is provided in the first argument.
#
# Argument 1: Number which deliminates the location between the top and bottom RM
#             Values larger than the provided value will use the top, etc.
find_mac_two_rm() {
	checking_value=$(grep RACK_MOUNT1_MAC1 $path | wc -l)
	if [ "$location" -gt $1 ] && [ "$checking_value" != 0 ]; then
		MAC=$(parse_bmc_mac $(cat $path | grep RACK_MOUNT1_MAC1))
	else
		MAC=$(parse_bmc_mac $(cat $path | grep RACK_MOUNT_MAC1))
	fi
}

if [ "$1" == "-d" ]; then
	MAC=$(parse_bmc_mac $(cat $path | grep ETH0))
elif [ "$1" == "-s" ]; then
	BMCMAC=$(cat $path | grep SWITCHMAC)
	if [ -z "$BMCMAC" ]; then
		echo -e "${LRed}Wasn't able to find a a switch MAC within the config file.${NC}"
		exit 1
	fi
	MAC=$(parse_bmc_mac $BMCMAC)
elif [ "$1" == "-l10" ]; then
	MAC=$2
	echo $MAC
elif [ "$model" == "C2398" ]; then
	find_mac_two_rm 20
elif [ "$model" == "C2298" ]; then
	find_mac_two_rm 21
else
	MAC=$(parse_bmc_mac $(cat $path | grep RACK_MOUNT_MAC1))
fi

RACKSN=$(grep RACKSN "$path" | awk -F'=' '{print $2}' | tr -d '\r')
echo -e "RACK SN found: ${LCyan}$RACKSN${NC}"
echo -e "MAC Address found: ${LCyan}$MAC${NC}"
ip=$(cat /var/lib/dhcpd/dhcpd.leases | grep -i $MAC -B8 | grep lease | cut -d " " -f2)
ip=($(echo $ip | tr "\n" "\n"))

if [ -z "$ip" ]; then
	echo -e "${Yellow}Could not find anything in IP neighbor. Trying dhcpd leases...${NC}"
	line_number=$(grep $MAC -i -n /var/lib/dhcpd/dhcpd.leases)
	IFS=":" read -ra split <<<"$line_number"
	line_number=$((${split[0]} - 6))
	line=$(cat -n /var/lib/dhcpd/dhcpd.leases | grep $line_number)
	IFS=" " read -ra split <<<"$line"
	ip=${split[1]}

elif [ ! -z "${ip[1]}" ]; then
	# check that all the ips are different
	all_same=true
	for i in "${ip[@]}"; do
		if [[ "$i" != "${ip[0]}" ]]; then
			all_same=false
			break
		fi
	done

	if [ "$all_same" = true ]; then
		echo -e "${Yellow}Multiple Addresses were found, but they were all the same"
		ip=${ip[0]}
	else
		echo -e "${Yellow}Multiple Addresses were found:${NC}"
		declare -i counter="0"
		for thing in "${ip[@]}"; do
			echo -e "${Green}$counter${NC}: $thing"
			counter+=1
		done
		echo -e "${Yellow}Please select the correct one: ${NC}"
		read selection
		ip=${ip[$selection]}
	fi

	echo -e "${LGreen}$ip${NC} was selected!"
fi

echo -e "IP Being used is: ${LGreen}$ip${NC}"

if [ "$1" == "-d" ]; then
	sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
elif [ "$1" == "-l10" ]; then
	BMCIP=$(sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip ". getMBinfo" | grep "BMCIP")
	ip=${BMCIP:6:40}
	echo -e "IP Being used is: ${LGreen}$ip${NC}"
	sshpass -p 'root' ssh -o 'StrictHostKeyChecking no' root@$ip
else
	sshpass -p '$pl3nd1D' ssh -o 'StrictHostKeyChecking no' root@$ip
fi
